update steps

diff --git a/cloudbuild/foundation/composer-apply.yaml b/cloudbuild/foundation/composer-apply.yaml
--- a/cloudbuild/foundation/composer-apply.yaml
+++ b/cloudbuild/foundation/composer-apply.yaml
@@ -32,7 +32,10 @@ steps:
     'plan',
     '-var=terraform_foundation_state_prefix=${_PREFIX}',
     '-var-file=env/${_TFVARS_FILE}.tfvars',
-    '-var=enforce=false'
+    '-var=enforce=false',
+    '-target=module.project_disable_sa_creation',
+    '-target=module.project_vm_os_login',
+    '-target=module.project_shielded_vms'
     # '-var=enforce_staging_project_vm_os_login=false',
     # '-var=enforce_staging_project_shielded_vms=false'
   ]
@@ -40,13 +43,29 @@ steps:
 - id: "composer - first apply and disable org policies"
   name: hashicorp/terraform:${_TAG}
   dir: 'environment/foundation/staging-project/cloud-composer'
-  entrypoint: /bin/sh
-  args:
-    - '-c'
-    - |
-      if ! terraform apply -auto-approve -var-file=env/${_TFVARS_FILE}.tfvars -var=terraform_foundation_state_prefix=${_PREFIX} -var="enforce=false" ; then
-        echo "Pipeline has failed, check terraform apply log output to determine error."
-      fi
+  args: [
+    'apply',
+    '-var=terraform_foundation_state_prefix=${_PREFIX}',
+    '-var-file=env/${_TFVARS_FILE}.tfvars',
+    '-var=enforce=false',
+    '-target=module.project_disable_sa_creation',
+    '-target=module.project_vm_os_login',
+    '-target=module.project_shielded_vms',
+    '-auto-approve'
+    # '-var=enforce_staging_project_vm_os_login=false',
+    # '-var=enforce_staging_project_shielded_vms=false'
+  ]
+
+# - id: "composer - first apply and disable org policies"
+#   name: hashicorp/terraform:${_TAG}
+#   dir: 'environment/foundation/staging-project/cloud-composer'
+#   entrypoint: /bin/sh
+#   args:
+#     - '-c'
+#     - |
+#       if ! terraform apply -auto-approve -var-file=env/${_TFVARS_FILE}.tfvars -var=terraform_foundation_state_prefix=${_PREFIX} -var="enforce=false" ; then
+#         echo "Pipeline has failed, check terraform apply log output to determine error."
+#       fi
 
 - id: "composer - second plan and ensure project policies are re-enabled"
   name: hashicorp/terraform:${_TAG}
@@ -55,14 +74,15 @@ steps:
   args:
     - '-c'
     - |
+      sleep 60
       terraform plan \
       -var-file=env/${_TFVARS_FILE}.tfvars \
       -var=terraform_foundation_state_prefix=${_PREFIX} \
-      -target=module.srde_project_disable_sa_creation \
+      -target=module.project_disable_sa_creation \
       -var="enforce=true" \
-      -target=module.srde_project_vm_os_login \
+      -target=module.project_vm_os_login \
       #-var="enforce_staging_project_vm_os_login=true" \
-      -target=module.srde_project_shielded_vms
+      -target=module.project_shielded_vms
       #-var="enforce_staging_project_shielded_vms=true"
 
 - id: "composer - second apply and ensure project policies are re-enabled"
@@ -75,11 +95,11 @@ steps:
       terraform apply -auto-approve \
       -var-file=env/${_TFVARS_FILE}.tfvars \
       -var=terraform_foundation_state_prefix=${_PREFIX} \
-      -target=module.srde_project_disable_sa_creation \
+      -target=module.project_disable_sa_creation \
       -var="enforce=true" \
-      -target=module.srde_project_vm_os_login \
+      -target=module.project_vm_os_login \
       # -var="enforce_staging_project_vm_os_login=true" \
-      -target=module.srde_project_shielded_vms
+      -target=module.project_shielded_vms
       # -var="enforce_staging_project_shielded_vms=true"
 
 - id: "staging project state pull - init"
